server:
  port: 8080
vnp:
  returnUrl: http://localhost:5173/confirm-payment
  tmnCode: 6A32GGY0
  secretKey: SWXLFPTXZYUNKQ39U7GTRCAQD7K9E008
  version: 2.1.0
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  baseUrl: https://sandbox.vnpayment.vn
  queryUri: /merchant_webapi/api/transaction

momo:
  partnerCode: MOMO
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  requestType: payWithMethod
  redirectUrl: http://localhost:5173/confirm-payment
  ipnUrl: https://example.com
  baseUrl: https://test-payment.momo.vn
  createUri: /v2/gateway/api/create
  queryUri:  /v2/gateway/api/query

ai:
  meta-llama:
    endpoint: ${AI_META_LLAMA_ENDPOINT:https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct/v1/chat/completions} # environment variable with a default value
    api-key: ${AI_HUGGING_FACE_API_KEY:YOUR_API_KEY} # environment variable with a default value

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:preg
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_CLIENT_ID} # environment variable with a default value
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_CLIENT_SECRET} # environment variable with a default value
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  mail:
    host: smtp.gmail.com
    port: 587
    username: mytutor.main.official@gmail.com
    password: ${MAIL_PASSWORD:YOUR_MAIL_PASSWORD} # environment variable with a default value
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
        debug: true